### ISSUE TITLE
Love your work

### ISSUE THREAD

**Issue by ghost** [SeerUK/tid#17]
Hey,

I started using this at work. Loving it so far. Can I help you out with docs or whatever? Wouldn't mind helping helping with something I love to use.

Best regards,

Sam

**Comment by seeruk** [comment]
Hi there,

I'm glad you like it! I'm always open to having contributions. If you do want to tackle something, there are a few other open issues I've not gotten around to just yet. How comfortable are you with Go?

**Comment by ghost** [comment]
I started tinkering with it last sunday, maybe I can help with docs or a small beginner issue?
